TEXI2PDF="/usr/bin/texi2pdf"
FILENAME="report"

all:
	@$(TEXI2PDF) $(FILENAME).tex
clean:
	rm -f $(FILENAME).aux $(FILENAME).d $(FILENAME).log $(FILENAME).pdf $(FILENAME).lof $(FILENAME).lot $(FILENAME).toc $(FILENAME).out
